version: 2.1

orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.12

jobs:
  build:
    docker:
      - image: 'circleci/node:13.2-browsers'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install third party npm dependencies
                command: npm install
      - run:
          name: Build Angular application for production
          command: npm run build-prod
      - run:
          name: Run unit tests
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      # Cache dist folder so it can be used by deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  deploy:
    docker:
      - image: 'circleci/python:2.7'
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - aws-s3/sync:
          from: dist/bookit-ng
          to: 's3://bookit-bucket/'
          overwrite: true

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: development
